site_name: CIRS Agent Docs
site_url: http://localhost:8020
docs_dir: site
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Architecture: architecture.md
  - Developer Guide: developer_guide.md
  - API Reference: api_reference.md
  - Database Schema: database_schema.md
  - GPU Setup: gpu_setup.md
  - Troubleshooting: troubleshooting.md
  - Release Process: release_process.md
  - User Manuals:
      - Ingestion Pipeline: user_manuals/ingestion_pipeline_guide.md
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
  - mermaid2
extra_css: []
