name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff bandit
      - name: Python lint
        run: ruff check .
      - name: Python security lint
        run: bandit -q -r backend || true
      - name: Python tests
        run: pytest -q || true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Frontend lint
        run: |
          cd frontend/chat_ui && npm ci && npm run lint --if-present || true
  build:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Images (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-compose.yml
          push: false
          provenance: false
          sbom: false
          no-cache: false
          platforms: linux/amd64
  scan:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy.sarif
          severity: CRITICAL,HIGH
      - name: Upload Trivy report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
  sbom:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM (repo)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom-repo.cdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-repo
          path: sbom-repo.cdx.json
